### ISSUE TITLE
Code doesn't compile in Java 1.7

### ISSUE THREAD

**Issue by sankarav** [UBOdin/jsqlparser#2]
This JSQLParser doesn't compile in Java 1.7 as it was using a Java 1.8 Generic feature. Changed to the bold lines in the following code snippet of **"JSqlParserCC.jj"** to make it work.

ItemsList ItemList() :
{
    ItemsList itemsList = null;
    Table table = null;
}
{
    (("(" 
        [   ( LOOKAHEAD(SubSelect()) itemsList=SubSelect() 
            | LOOKAHEAD(ExpressionList()) itemsList=ExpressionList() 
            )] ")")
        |   LOOKAHEAD(Table()) table = Table() {
            // Encode `x IN tableName` as `x in (SELECT * FROM tableName)`
            SubSelect subSel = new SubSelect();
            PlainSelect body = new PlainSelect();
            subSel.setAlias(table.getName());
            subSel.setSelectBody(body);
            body.setFromItem(table);
                        ~~body.setSelectItems(Arrays.asList(
                new ListAllColumns()
            ));~~
                        **List<SelectItem> si = new ArrayList<SelectItem>();
                        si.add(new AllColumns());
                        body.setSelectItems(si);**
            itemsList = subSel;
        }
    ) { return itemsList; }
}

**Comment by okennedy** [comment]
Could you create a pull request please.
